name: PBRP

on:
  workflow_dispatch:
  push:
    # only trigger on branches, not on tags
    branches: '**'


jobs:
  build:
    name: PBRP Build CI
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Installing build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc schedtool
          sudo ln -f -s /usr/bin/python2.7 /usr/bin/python
      - name: Syncing PBRP sources
        run: |
          mkdir ~/PBRP
          cd ~/PBRP
          mkdir ~/.bin
          curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          python3 ~/.bin/repo init --depth=1 -u https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-11.0
          python3 ~/.bin/repo sync -c --optimized-fetch
          git clone --branch android-11 --single-branch https://github.com/LunaOSS/recovery-device_xiaomi_sweet.git ~/PBRP/device/xiaomi/sweet
          chmod -R a+x device/xiaomi/sweet
      - name: Building PBRP
        run: |
          cd ~/PBRP
          source build/envsetup.sh
          export LC_ALL=C
          lunch omni_sweet-eng
          mka pbrp
      - name: Uploading PBRP builds
        uses: actions/upload-artifact@v2
        with:
          name: pbrp-sweet
          path: /home/runner/PBRP/out/target/product/dura64/recovery.*
