name: TWRP

on:
  workflow_dispatch:


jobs:
  build:
    name: TWRP Upload CI
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Uploading TWRP builds
        uses: actions/upload-artifact@v2
        with:
          name: twrp
          path: /home/runner/TWRP/out/target/product/sweet/recovery.*
